### ISSUE TITLE
US#1 Como usuario, es ideal una bienvenida de la aplicación para disponer de información y de que trata dicha aplicación

### ISSUE THREAD

**Issue by Aldofn8** [pgCatamarca2021fs/aula2-grupoe-team-2e#1]
## *Descripción*
Debemos diseñar una bienvenida con la información necesaria de que tratara la aplicación web. Así los nuevos usuarios puedan disponer de información básica como: Criptomonedas a trabajar, objetivo del sitio, creadores y metas a conseguir entre otras.
## *Criterios de Aceptación*
Amigable y ser un MVP(mínima versión responsiva). En lo posible en la página principal y sea legible.
## *Estimación*
 3 días

**Comment by MicaMonje** [comment]
Se implemento la bienvenida mendiante un carrusel y tarjetas que brindan informacion sobre la pagina.
