### ISSUE TITLE
US#20 Diseño lógico de la base de datos.

### ISSUE THREAD

**Issue by MATMA89** [pgCatamarca2021fs/aula2-grupoe-team-2e#20]
## *Descripción*
Debemos diseñar el diagrama conceptual y lógico de la base de datos.
## *Criterios de Aceptación*

- Exponer el diagrama en pdf.
- Diagrama normalizado.

## *Estimación*
 3 días

**Comment by lionel1014** [comment]
Tengo estas ideas para el modelo conceptual
