### ISSUE TITLE
US#3 Como usuario, quiero poder comprar y/o vender criptomonedas, para cambiar a una diferente moneda

### ISSUE THREAD

**Issue by Aldofn8** [pgCatamarca2021fs/aula2-grupoe-team-2e#3]
## *Descripción*
El usuario va ingresar en la Comprar/Vender criptomonedas, el mismo selecciona la moneda con la cual se desea operar, el tipo de operacion(compra/venta), y la cantidad de monedas que desea operar. Va haber una celda en la cual puede ingresar un monto(pero en pesos para operar con el valor de una moneda conocida) .
## *Criterios de Aceptación*
Crear los componentes necesarios para cada operación. Componente de compra y un componente de venta. Lo cual, también se necesita un maquetado de un formulario básico para realizar estas operaciones.
Que los depósitos y retiros que se realicen en la aplicación estén verificados por la entidad que los realiza.
## *Estimación*
3 dias

**Comment by MicaMonje** [comment]
Se creo un segmento en el cual se ha incorporado los requerimientos de compra/venta. Queda por modificar el requerimiento de intercambios.
